### ISSUE TITLE
Release v3 as a bridge to Laminas or Symfony Cache

### ISSUE THREAD

**Issue by rogervila** [doctrine/cache#409]
Hello,

I propose doing something similar as [container-interop/container-interop](https://github.com/container-interop/container-interop): release a new version that, while maintaining the same API as the previous one, it acts as a bridge to another maintained package.

The is a PR on doctrine/DoctrineModule that is doing that (https://github.com/doctrine/DoctrineModule/pull/796) but it may make more sense to implement it here.

What do you think @Ocramius @driehle @greg0ire @beberlei?

Thank you.

BTW, I would work on that PR if you agree.

**Comment by stof** [comment]
container-interop did that because its API was the same than the PSR-11 interface, so it could just extend it.

The doctrine/cache API is not the same. That's why doctrine/cache v2 was released containing only the PSR-6 adapter bridging to PSR-6, but it cannot be more transparent than that (the interfaces are not the same)

**Comment by rogervila** [comment]
Thank you @stof.

The idea is to make it easier to migrate other doctrine packages that rely on doctrine/cache to new versions without introducing breaking changes (as in https://github.com/doctrine/DoctrineModule/pull/796).

Let's see if this idea gets some support. Otherwise, I will close the PR.

**Comment by stof** [comment]
Well, doctrine/cache v2 *already* makes it easy to migrate to PSR-6 (which is the replacement that was chosen for usages in the various Doctrine projects).
In your DoctrineModule, as Laminas Cache does not implement PSR-6, you will still need a PSR-6 wrapper around Laminas Cache (the non-deprecated way to configure the ORM is to give it a PSR-6 cache pool). So you could still rely on the doctrine/cache PSR-6 adapters in your module that are already available in v2.

To me, there is no benefit providing a direct wrapper for Laminas Cache implementing the doctrine/cache interface, as that won't help you migrating to non-deprecated APIs in the ORM (or the ODM or other Doctrine projects using a cache anyway).

**Comment by stof** [comment]
Btw, as the title mentions both Laminas and Symfony, note that symfony/cache implements PSR-6 so the bridging logic already covers it.

**Comment by derrabus** [comment]
Can you please elaborate why v2 isn't already what you ask for? I honestly don't understand this proposal.

**Comment by rogervila** [comment]
HI, @derrabus @stof 

The idea was to integrate the Symfony or laminas cache bridge inside the library itself but, after reviewing its usage across other libraries, I see that is the responsibility of other libraries to do so (as in https://github.com/doctrine/DoctrineModule/pull/796), so I am closing this issue.
